#ifndef LKM_DRIVER_DEFS_HH
#define LKM_DRIVER_DEFS_HH

#define LKM_DRIVER_CW 0x00
#define LKM_DRIVER_CCW 0x01
#define MOTOR_SERIES_MS 0x00
#define MOTOR_SERIES_MF 0x01
#define MOTOR_SERIES_MG 0x02
#define MF_SERIES_MAX_TORQUE 16.5f
#define MG_SERIES_MAX_TORQUE 33.0f
#define MS_SERIES_MAX_POWER 850
#define ENCODER_TYPE_14_BIT 0x00
#define ENCODER_TYPE_16_BIT 0x01
#define ENCODER_TYPE_18_BIT 0x02

#endif  // !LKM_CAN_DRIVER_DEFS_HH
